
name: Manual Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select deployment environment"
        required: true
        type: choice
        options:
          - DEV
          - SIT
          - PAT
          - PROD

permissions:
  contents: read

jobs:
  terraform-validate:
    name: Validate Terraform
    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Initialize
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Display Selected Environment
        run: echo "Selected environment: ${{ inputs.environment }}"
